name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Print versions
      - name: Powershell Environment
        shell: pwsh
        run: |
          $PSVersionTable
          
      # Install TeamViewerPS
      - name: Install TeamViewerPS
        shell: pwsh
        run: |
          $ProgressPreference='SilentlyContinue'
          Install-Module TeamViewerPS -Force -SkipPublisherCheck -Scope CurrentUser -Verbose

      # Run tests
      - name: Run Pester
        shell: pwsh
        run: |
          $ProgressPreference='SilentlyContinue'
          Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser `
            -RequiredVersion 5.1.1 -Verbose
          Invoke-Pester $env:GITHUB_WORKSPACE -Output Detailed -CI
